Models/ErrorViewModel.cs
using System;

namespace MarvelMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/UserData.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MarvelMVC.Models
{
    public class UserData
    {
        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage = "First name is required ")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Last name is required ")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Location is required ")]
        public string Location { get; set; }
        [Required(ErrorMessage = "Phone Number is required ")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "Email is required ")]
        [EmailAddress(ErrorMessage = "Please enter a valid email address")]
        public string Email { get; set; }

    }
}

Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace MarvelMVC.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MarvelMVC.Models;

namespace MarvelMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UserController.cs
using MarvelMVC.DatabaseContext;
using MarvelMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarvelMVC.Controllers
{
    public class UserController : Controller
    {
        private readonly AppDbContext _context;
        public UserController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var user = _context.UserDataTable.ToList();
            return View(user);
        }
        public IActionResult AddUser()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddUser(UserData user)
        {
            if (ModelState.IsValid)
            {
                await _context.UserDataTable.AddAsync(user);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View();
        }

    }
}

Views/About/index.cshtml
@{
    ViewData["Title"] = "About Page";
}

<div class="text-center">
    <h1 class="display-4">About me</h1>
     <table>
        <thead>
            <tr>
                <th>Name</th>
                <td>Toluwanimi</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>Email Address</th>
                <td>abimbolaoladejo4@gmail.com</td>
            </tr>
        </tbody>
    </table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MarvelMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MarvelMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">About Me</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MarvelMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/User/AddUser.cshtml
@model UserData

@{
    ViewData["Title"] = "User Profiles";
}

<h2>Add Users </h2>

<div class="row">
    <div class="col-5">
        <form asp-controller="User" asp-action="AddUser" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="text" asp-for="FirstName" class="form-control mt-2" placeholder="First Name" />
            <input type="text" asp-for="LastName" class="form-control mt-2" placeholder="Last Name" />
            <input type="text" asp-for="Location" class="form-control mt-2" placeholder="Location" />
            <input type="tel" asp-for="PhoneNumber" class="form-control mt-2" placeholder="Phone Number" />
            <input type="email" asp-for="Email" class="form-control mt-2" placeholder="Email Address" />
            <button type="submit" class="btn btn-primary w-100 mt-2">Add</button>
        </form>
    </div>
</div>

Views/User/index.cshtml
@model List<UserData>
    
@{
    ViewData["Title"] = "User Profiles";
}

<h2>All Users </h2>
<a asp-controller="User" asp-action="AddUser" class="btn btn-primary">Add User</a>
<div class="text-center">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>PhoneNumber</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>